### PR TITLE
Adds handling of virtual functions for List schema objects

### PR DESCRIPTION
**Pull request by trystant**
I don't know if you'd prefer to mock out those objects instead, but I used this in order to do testing on my Keystone app. Thanks for your help!

### CODE REVIEW

**Comment by webteckie** [comment]
Thanks @trystant Since it worked for you I accepted it as-is.  If need be we can refactor later.

**Comment by webteckie** [comment]
Hi @trystant if you have a sample test for virtuals I think it would be nice to add it to https://github.com/webteckie/keystonejs-stub/blob/master/__tests__/sampleListModel-spec.js

**Comment by trystant** [comment]
Hey @webteckie adding one explicitly makes sense. I had thought that the non failing with a Keystone model which had virtual methods would be sufficient, but it does help to be explicit in describing behavior. One test coming up!

**Comment by trystant** [comment]
I am going to start with a simple "exists" test and change the virtual function in the code to refer to the actual model. There's something I missed in carrying virtuals over which keeps them from being used in current testing and I need to get to the bottom of that.

**Pull request merged**
